openapi: 3.0.1
info:
  title: Message API
  version: 1.0.0
servers:
  - url: https://{restapi_id}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      region:
        default: us-east-1
      stage:
        default: dev
paths:
  /messages:
    post:
      summary: Create a new message
      operationId: createMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
            example:
              metadata:
                message_time: "2023-12-10T22:02:38Z"
                company_id: "e0721e56-fb09-4273-ae74-7bcbc92d43eb"
                message_id: "fc0daad3-4f10-4d15-b8c6-276cca111e87"
              data:
                order_id: "a929b88e-bc47-4f7d-9584-61c3c94ad2f2"
                order_time: "2023-12-10T22:00:00Z"
                order_amount: 20
      responses:
        "201":
          description: Message stored successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message_id:
                    type: string
        "200":
          description: Duplicate message (idempotent)
        "400":
          description: Validation error

  /messages/{message_id}:
    get:
      summary: Get message by ID
      operationId: getMessageById
      parameters:
        - in: path
          name: message_id
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: company_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Message found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoredMessage'
        "404":
          description: Message not found

components:
  schemas:
    Message:
      type: object
      properties:
        metadata:
          type: object
          required: [message_time, company_id, message_id]
          properties:
            message_time:
              type: string
              format: date-time
            company_id:
              type: string
              format: uuid
            message_id:
              type: string
              format: uuid
        data:
          type: object
          required: [order_id, order_time, order_amount]
          properties:
            order_id:
              type: string
              format: uuid
            order_time:
              type: string
              format: date-time
            order_amount:
              type: number
    StoredMessage:
      type: object
      properties:
        company_id:
          type: string
        message_id:
          type: string
        metadata:
          type: object
        data:
          type: object
        s3_key:
          type: string
